services:
  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - "5672:5672"
    security_opt:
      - no-new-privileges:true

  kafka:
    image: confluentinc/cp-kafka:8.0.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: "1"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://127.0.0.1:9092"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: "1"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    security_opt:
      - no-new-privileges:true

  nats:
    image: nats
    command: -js
    ports:
      - 4222:4222
      - 8222:8222  # management
    security_opt:
      - no-new-privileges:true

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    security_opt:
      - no-new-privileges:true

  faststream:
    build: .
    volumes:
      - ./:/src
      - /src/.venv/
    network_mode: "host"
    tty: true
