version: "3"
services:
    # zookeeper:
    #     ports:
    #         - "${PORT_PREFIX}2181:2181"

    # kafka:
    #     ports:
    #         - "${PORT_PREFIX}9092:9092"

    fast-kafka-api:
        image: $DOCKER_IMAGE
        hostname: fast-kafka-api
        container_name: fast-kafka-api
        environment:
            DOMAIN: $DOMAIN
            KAFKA_HOSTNAME: $KAFKA_HOSTNAME
            KAFKA_PORT: $KAFKA_PORT
            DB_DOWNLOAD_SIZE: $DB_DOWNLOAD_SIZE
            ROOT_PATH: $ROOT_PATH
            KAFKA_API_KEY: $KAFKA_API_KEY
            KAFKA_API_SECRET: $KAFKA_API_SECRET
        # deploy:
        #     resources:
        #         reservations:
        #             devices:
        #             - driver: nvidia
        #               device_ids: ['all']
        #               capabilities: [gpu]
        # depends_on:
        #     - kafka
