version: "3"
services:
    zookeeper:
        image: wurstmeister/zookeeper
        hostname: zookeeper
        container_name: zookeeper

    kafka-1:
        image: wurstmeister/kafka
        hostname: kafka-1
        environment:
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTER:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: INTER://kafka-1:9092
            KAFKA_LISTENERS: INTER://kafka-1:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: INTER
            KAFKA_CREATE_TOPICS: >-
              training_request:${NUM_PARTITIONS:-6}:${REPLICATION_FACTOR:-3},
              training_status:${NUM_PARTITIONS:-6}:${REPLICATION_FACTOR:-3},
              prediction_request:${NUM_PARTITIONS:-6}:${REPLICATION_FACTOR:-3},
              prediction_status:${NUM_PARTITIONS:-6}:${REPLICATION_FACTOR:-3}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - zookeeper

    kafka-2:
        image: wurstmeister/kafka
        hostname: kafka-2
        environment:
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTER:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: INTER://kafka-2:9092
            KAFKA_LISTENERS: INTER://kafka-2:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: INTER
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - zookeeper

    kafka-3:
        image: wurstmeister/kafka
        hostname: kafka-3
        environment:
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTER:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: INTER://kafka-3:9092
            KAFKA_LISTENERS: INTER://kafka-3:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: INTER
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - zookeeper