version: "3"
services:
    fastkafka-devel:  #nosemgrep
        image: ghcr.io/airtai/nbdev-mkdocs
        hostname: $DOCKER_COMPOSE_PROJECT-devel
        container_name: $DOCKER_COMPOSE_PROJECT-devel
        ports:
            - "${PORT_PREFIX}888:8888"
            - "${PORT_PREFIX}400:4000"
            - "${PORT_PREFIX}600:6006"
        volumes:
            - $AIRT_PROJECT:/work/fastkafka
            - /etc/passwd:/etc/passwd
            - /etc/group:/etc/group
            - /etc/shadow:/etc/shadow
            - $HOME/.ssh:$HOME/.ssh
            - $HOME/.gitconfig:/root/.gitconfig
        environment:
            USER: $USER
            USERNAME: $USERNAME
            PRESERVE_ENVS: $PRESERVE_ENVS
            OPENAI_API_KEY: $OPENAI_API_KEY
