version: "3"
services:
    fast-kafka-api:
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - /etc/letsencrypt:/letsencrypt
        environment:
            RUN_NGINX: "true"
