site_name: FastStream
site_description: ''
site_url: https://faststream.airt.ai/
site_author: airt
copyright: '&copy; 2023 <a href="https://airt.ai/" target="_blank" rel="noopener">airt</a>'
docs_dir: docs

theme:
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: custom
    accent: cyan
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: custom
    accent: cyan
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  - navigation.indexes
  - content.tooltips
  - navigation.path
  - content.code.annotation
  - content.code.copy
  - content.code.select
  i18n:
    prev: 'Previous'
    next: 'Next'
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil-circle-outline
  logo: assets/img/logo.svg
  favicon: assets/img/logo.svg

extra_css:
  - stylesheets/extra.css

repo_name: airtai/fastkafka
repo_url: https://github.com/airtai/fastkafka
edit_uri: ''

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          import:
          - https://docs.python.org/3/objects.inv
          options:
            heading_level: 2
            show_source: true
            show_category_heading: true
            show_root_heading: true
            show_if_no_docstring: true
            separate_signature: true
            show_signature_annotations: true
  # build a site link social preview card
  - social:
      enabled: !ENV [CI, false]
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
  - literate-nav:
      nav_file: SUMMARY.md

markdown_extensions:
  toc:
    permalink: "#"
  markdown.extensions.codehilite:
    guess_lang: false
  mdx_include:
    base_path: .
  admonition: null
  codehilite: null
  extra: null
  pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
  pymdownx.tabbed:
    alternate_style: true
  attr_list: null
  md_in_html: null

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/CJWmYpyFbc
    - icon: fontawesome/brands/github-alt
      link: https://github.com/airtai/fastkafka
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/airt_AI
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/airt.ai.api/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/airt-ai/

  alternate:
    - link: /
      name: en - English

  version:
    provider: mike
