name: Auto-fix Markdown code blocks

permissions:
  issues: write
  discussions: write
  pull-requests: write

on:
  issues:
    types:
      - opened
      - edited
  discussion:
    types:
      - created
      - edited
  pull_request_target:
    types:
      - opened

jobs:
  fix-md-code-blocks:
    runs-on: ubuntu-latest
    steps:
      - id: fixer
        uses: mahenzon/md-code-block-auto-lang@cf7aa43dc0026951952b6ae45609ef4539223f05 # v1.0.0
        with:
          github-token: ${{ secrets.AUTOMERGE_TOKEN }}
          language: python
          silent: true

      - name: Show fix result count
        run: echo "Fixed ${STEPS_FIXER_OUTPUTS_FIXES} code blocks"
        env:
          STEPS_FIXER_OUTPUTS_FIXES: ${{ steps.fixer.outputs.fixes }}
