name: Deploy FastKafka documentation to the GitHub Pages

on:
  push:
    branches: [ "main", "master"]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: airtai/workflows/fastkafka-docusaurus-ghp@main
