name: Generate API References documentation

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - ready_for_review
    paths:
      - faststream/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  check-docs-changes:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        shell: bash
        # should install with `-e`
        run: |
          set -ux
          python -m pip install uv
          uv pip install --system -e .[dev]
      - name: Run build docs
        run: bash scripts/build-docs.sh
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: generate API References"
