name: Event Notifier

on:
  issues:
    types: [opened, labeled, reopened]
  pull_request_target:
    types: [opened, reopened] # zizmor: ignore[dangerous-triggers]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number || github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  issues: read
  pull-requests: read

jobs:
  notify:
    name: "Send Telegram notification for new issue or opened pull request"
    runs-on: ubuntu-latest
    if: github.event.action == 'opened' || github.event.action == 'reopened'
    steps:
      - name: Send Telegram notification for new issue or opened pull request
        uses: sehat1137/telegram-notifier@34118668d9efc950ec06f9a3e2cd3a1a3e9e2b63 # v1.4.1-pre-release
        with:
          tg-bot-token: ${{ secrets.TELEGRAM_TOKEN }}
          tg-chat-id: ${{ secrets.TELEGRAM_TO }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
  notify-oss-board:
    name: "Send Telegram notification to OSS board"
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'issues' &&
      contains(github.event.issue.labels.*.name, 'good first issue')
    steps:
      - name: Send Telegram notification to OSS board
        uses: sehat1137/telegram-notifier@34118668d9efc950ec06f9a3e2cd3a1a3e9e2b63 # v1.4.1-pre-release
        with:
          tg-bot-token: ${{ secrets.TELEGRAM_TOKEN }}
          tg-chat-id: ${{ secrets.GFI_CHAT }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
