name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  mypy_static_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: airtai/workflows/airt-mypy-check@main
  bandit_static_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: airtai/workflows/airt-bandit-check@main
  semgrep_static_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: airtai/workflows/airt-semgrep-check@main
  test:
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os:  [ubuntu]
        version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Install quarto
        run: |
          wget -q https://www.quarto.org/download/latest/quarto-linux-amd64.deb
          sudo dpkg -i quarto-linux-amd64.deb
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.version }}
          cache: "pip"
          cache-dependency-path: settings.ini
      - name: Install project lib
        run: |
          python -m pip install --upgrade pip
          test -f setup.py && pip install -e ".[dev]"
          pip install ".[dev]"
      - name: Install docs and testing deps
        run: |
          fastkafka docs install_deps
          fastkafka testing install_deps
      - name: Run nbdev tests
        if [[ `git status --porcelain -uno` ]]; then
          git diff
          echo "git status is not clean"
          false
        fi
        echo "Trying to strip out notebooks"
        nbdev_clean
        echo "Check that strip out was unnecessary"
        git status -s # display the status to see which nbs need cleaning up
        if [[ `git status --porcelain -uno` ]]; then
          git status -uno
          echo -e "!!! Detected unstripped out notebooks\n!!!Remember to run nbdev_install_hooks"
          false
        fi
        nbdev_export
        if [[ `git status --porcelain -uno` ]]; then
          echo "::error::Notebooks and library are not in sync.  Please run nbdev_export."
          git status -uno
          git diff
          exit 1;
        fi
        if [ ! $SKIP_TEST ]; then
          nbdev_test --flags "$FLAGS"
        fi
      - name: Test building docs with nbdev-mkdocs
        run: |
          nbdev_mkdocs docs
          if [ -f "mkdocs/site/index.html" ]; then
            echo "docs built successfully."
          else
            echo "index page not found in rendered docs."
            ls -la
            ls -la mkdocs/site/
            exit 1
          fi
